Haikal analytics refactor compute path
haikalpribadi/grakn pull request #5
Opened 2018-05-18 21:18 UTC by lolski

# Why is this PR needed?

# What does the PR do?

# Does it break backwards compatibility?

# List of future improvements not on this PR

2018-05-20 23:07 UTC, haikalpribadi commented
The test fails, @lolski. I think it causes a compilation bug in `ComputeJob.java`.

2018-05-20 23:08 UTC, haikalpribadi requested changes
The compilation fails at ComputeJob.java

2018-05-21 10:02 UTC, lolski commented
@haikalpribadi forgot to include that change from my other branch. fixed!

Now it complains about
```
error: Server does not allow request for unadvertised object b0ab1c80bf398ef88762c7e670343b99987ad700
Fetched in submodule path 'grakn-spec', but it did not contain b0ab1c80bf398ef88762c7e670343b99987ad700. Direct fetching of that commit failed.
```

I have never experienced this error before but it sounds like we're missing a commit `b0ab1c80bf398ef88762c7e670343b99987ad700` from the `grakn-spec` submodule. Looking into this.

2018-05-21 16:50 UTC, haikalpribadi approved these changes

2018-05-21 16:51 UTC, merged